### ISSUE TITLE
Systemic 2.173 Tutorial crashes 

### ISSUE THREAD

**Issue by tckosvic** [stefano-meschiari/Systemic2#9] opened 2014-11-17 17:52 UTC
Stefano,  just got Systemic 2.173 with R 3.1.2  fired up and ran tutorial (tut) and got a crash below.  It happened on next step after loading HD115617.sys data.  Let me know if this is my problem or someother.
Thanks, Tom Kosvic

 *** caught segfault ***
address 0xb44ad000, cause 'memory not mapped'

Traceback:
 1: .dyncall.default(<pointer: 0xb47f5130>, "*<gsl_matrix>iidii*diB)*<gsl_matrix>",     ...)
 2: ok_resample_curve(per, 0, 1, 1, 10000, 2000, .periodogram.tol,     5, TRUE)
 3: .dyncall.default(<pointer: 0xb47f50b0>, "p)I", ...)
 4: ok_matrix_rows(m)
 5: .gsl_matrix_to_R(ok_resample_curve(per, 0, 1, 1, 10000, 2000,     .periodogram.tol, 5, TRUE), free = TRUE)
 6: kperiodogram(k, samples = getOption("systemic.psamples", 50000),     pmin = getOption("systemic.pmin", 0.5), pmax = getOption("systemic.pmax",         20000), .keep.h = TRUE)
 7: .gui.update(k, calculate = calculate)
 8: kupdate(k)
 9: kadd.data(tut, c("datafiles/HD115617_AAT.vels", "datafiles/HD115617_KECK.vels"))
10: eval(expr, envir, enclos)
11: eval(parse(text = substr(line, 2, nchar(line))))
12: NEXT()
aborting ...

I'm sorry, tom. I'm afraid I can't do that... :(

It appears the Console (or its R kernel) has crashed.

**Comment by ddellaro** [comment] 2015-02-03 22:29
I haven't experienced this type of crash, but here's an error message I get occasionally while using the tutorial:
Warning message:
In if (class(ka)=="kernel") { :
the condition has length > 1 and only the first element will be used.

Has anyone seen this before, and if so, can you tell me the cause?

Thanks!
Devin

**Comment by stefano-meschiari** [comment] 2015-03-10 22:45
This is fixed in 2.18.

**Closed by stefano-meschiari** 2015-03-10 22:45 UTC
